apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-nodepool
spec:
  template: 
    metadata:  
      labels:
        billing-team: my-team
        # node-type: gpu
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: gpu-nodeclass
      taints: 
        - key: "nvidia.com/gpu" 
          value: "Exists" 
          effect: "NoSchedule" 
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["g"]
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["g4dn","g5","g6"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: ["xlarge", "2xlarge", "12xlarge"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
  limits:
    nvidia.com/gpu: 2
    cpu: 24
    memory: 30Gi




